apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ai-ccps
  labels:
    app: ai-ccps
spec:
  minReplicas: 2
  maxReplicas: 10

  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 70
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-ccps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ccps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-ccps
  template:
    metadata:
      name: ai-ccps
      labels: 
        app: ai-ccps
    spec:
      hostname: batman
      subdomain: ai-ccps
      containers:
      - name: ai-ccps
        image: docker.io/ksun4131/django-ai
        command: ['python3']
        args: ['manage.py', 'runserver', '0.0.0.0:80']
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2000m
            memory: 4000M
          requests:
            cpu: 1500m
            memory: 3500M
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ai-ccps
spec:
  ports:
  - name: svc-ai-ccps
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: ai-ccps
  type: LoadBalancer