apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ccps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-ccps
  template:
    metadata:
      name: ai-ccps
      labels: 
        app: ai-ccps
    spec:
      containers:
      - name: ai-ccps
        image: docker.io/ksun4131/django-ai
        command: ['python3']
        args: ['manage.py', 'runserver', '0.0.0.0:80']
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ai-ccps
spec:
  ports:
  - name: svc-ai-ccps
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: ai-ccps
  type: LoadBalancer