kind: Deployment
apiVersion: apps/v1
metadata:
  name: main-react-app
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: main-react-app
  template: 
    metadata:
      labels:
        app: main-react-app
    spec: 
      containers:
        - name: main-react-app
          image: localhost:5000/main-react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: main-react-app
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: main-react-app
    
 
